### ISSUE TITLE
Chapter 8 should mention cmake_parse_arguments

### ISSUE THREAD

**Issue by robertodr** [dev-cafe/cmake-cookbook#237]
`cmake_parse_arguments` seems to be the way to go when writing functions and macros:
https://cmake.org/cmake/help/v3.5/command/cmake_parse_arguments.html#command:cmake_parse_arguments

**Comment by TheErk** [comment]
That's pretty true. Now you should know that cmake_parse_arguments has not always been a builtin cmake command. In fact as far as `git tag --contains e8b148318f1fab26b2289cadc2d0c5e12201169d`
is right, it seems to become a command with 3.5.0. Before that you had a module.
Your example shows module inclusion with include(CMakeParseArguments) with cmake 3.5.0 and after this not necessary (but harmless) anymore.
See reminder here:
https://cmake.org/cmake/help/v3.5/module/CMakeParseArguments.html

**Comment by robertodr** [comment]
We do this other places. Closed.
