### ISSUE TITLE
AppVeyor chapter 4 failures in testing step

### ISSUE THREAD

**Issue by robertodr** [dev-cafe/cmake-cookbook#344]
## Current Behavior
MSYS/Ninja generators:
- chapter 4, recipe 7 (using `COST`) Tests fail.

Visual Studio generators:
- chapter 4, recipe 1 (simple unit test) Tests fail, possibly `cmake --build . --target test` does not work with VS.
- chapter 4, recipe 2 (Catch) Tests fail, possibly `cmake --build . --target test` does not work with VS.
- chapter 4, recipe 3 (GTest) Can't link against GTest library
- chapter 4, recipe 4 (Boost test) Can't find Boost test
- chapter 4, recipe 5 Tests fail, possibly `cmake --build . --target test` does not work with VS.
- chapter 4, recipe 6 Tests fail, possibly `cmake --build . --target test` does not work with VS.
- chapter 4, recipe 7 Tests fail, possibly `cmake --build . --target test` does not work with VS.
- chapter 4, recipe 8 Tests fail, possibly `cmake --build . --target test` does not work with VS.
- chapter 4, recipe 9 Tests fail, possibly `cmake --build . --target test` does not work with VS.
- chapter 4, recipe 10 Tests fail, possibly `cmake --build . --target test` does not work with VS.

**Comment by bast** [comment]
For context on what has been tried see #383.

**Comment by bast** [comment]
Remaining issues:
- [ ] 4/1 bash
- [ ] 4/1 subprocess
- [ ] 4/8

**Comment by bast** [comment]
The reason 4/8 fails are again symlinks not understood and these symlinks are present in the zip file (?)
