### ISSUE TITLE
Move repo to dev-cafe/cmake-cookbook

### ISSUE THREAD

**Issue by bast** [dev-cafe/cmake-cookbook#348]
Motivation:
- move away from personal namespace to allow others to join maintenance effort
- rename repo to be closer to the book title

This will require relocating badges and also switching things on the CI side.

**Comment by robertodr** [comment]
* Put up a notice on `README.md` redirecting to the new home and also stating that this repo is "deprecated".

**Comment by bast** [comment]
Repo moved. Now adjusting Travis, Appveyor, and badges.

**Comment by robertodr** [comment]
Fantastic!

**Comment by TheErk** [comment]
Nice right.
Even forked repo (like) mine: https://github.com/theerk/cmake-recipes seems to follow the move repo now!!

**Comment by TheErk** [comment]
If it has been the case, It wouldn't have really been a big deal.
The only thing I had to do was to switch remote upstream url with:
git remote set-url upstream git@github.com:dev-cafe/cmake-cookbook.git

**Comment by bast** [comment]
I think the move/rename functionality is very nicely implemented to avoid link rot and confusion.

**Comment by TheErk** [comment]
And then rename my repo accordingly.
https://github.com/TheErk/cmake-cookbook

and all is clean as if it was named like this since day 1.
