### ISSUE TITLE
Document that Anaconda is not tested on Ninja

### ISSUE THREAD

**Issue by bast** [dev-cafe/cmake-cookbook#353]
It should be noted in the README.md (or wherever you see appropriate) and mentioned in the book.
The reason why I chose to not test on Ninja is to limit the matrix size assuming that test coverage would not significantly increase by extending to Ninja.

**Comment by robertodr** [comment]
Coverage won't increase. One thing you might want to consider is to test Anaconda _only with Ninja_ (feasible if it's only C++ that's going on for those recipes) which might give some decent build-time speedup.

**Comment by bast** [comment]
Yes we only test C++. I have nothing against testing only Ninja with Anaconda although build speed should not matter here (I am not sure what times out) and I believe Ninja is less mainstream so perhaps we should test Unix Makefiles to make sure it works for the average user?

**Comment by robertodr** [comment]
The timeout seems to come from installing packages into a conda environment, so Ninja or Unix Makefiles won't make a difference, I agree. I think the only case where Unix Makefiles work and Ninja doesn't is for Fortran, so no degradation in coverage with preferring Ninja over Unix Makefiles for C++-only stuff.

**Comment by bast** [comment]
So we agree that we do not want to test Anaconda on Ninja? I can extend testing towards Ninja, no problem. Just was not sure what the conclusion is from this discussion above.

**Comment by robertodr** [comment]
It's ok to skip ninja. Let's just put a sentence in the recipe's readme.md

**Comment by robertodr** [comment]
Testing with Ninja would require setting the generator in the conda recipe itself, _i.e._ modifying the `CMAKE_GENERATOR` environment variable set when issuing `conda build`. Though this is certainly feasible, it doesn't add anything to the CMake side of things and would complicate a bit our testing framework. In hindsight, adding a documentation note is not even necessary, as long as we refer to this: https://conda.io/docs/user-guide/tasks/build-packages/environment-variables.html#environment-variables-set-during-the-build-process

**Comment by bast** [comment]
Closing. After reading and thinking I realize that this does not need mentioning.
