### ISSUE TITLE
Check whether "Running a custom command at build-time II" requires C

### ISSUE THREAD

**Issue by bast** [dev-cafe/cmake-cookbook#372]
See #370.

**Comment by TheErk** [comment]
I don't think that running a custom command requires anything beside the command run being available,
[at build time].

Did you experienced otherwise?

**Comment by bast** [comment]
Sorry, perhaps confusing issue title. I wanted to not forget to check whether we need "C" in:
https://github.com/dev-cafe/cmake-cookbook/blob/master/chapter-05/recipe-04/cxx-example/CMakeLists.txt#L3

Probably not needed but I opened this issue so that the question does not get lost in a comment to a closed PR.

**Comment by robertodr** [comment]
Looked at it. C is not needed. It's in an upcoming pr.

**Comment by TheErk** [comment]
ok fine.

**Comment by robertodr** [comment]
Issue was fixed, closing.
