### ISSUE TITLE
Chapter 9 failure on Appveyor

### ISSUE THREAD

**Issue by robertodr** [dev-cafe/cmake-cookbook#381]
#### MSYS2

- recipe 4, Boost.Python. No mattter how hard I try, Boost.Python is not found. Yet it is installed using pacman (and other libraries are found in other recipes)
- recipe 5, pybind11. Tests are not run or fail.
- recipe 6, CFFI. Tests are not run of fail.

#### Visual Studio

- recipe 3, Cython. Tests are not run or fail. 
- recipe 4, Boost.Python. No mattter how hard I try, Boost.Python is not found. Yet it is installed using VcPkg and I correctly pass the toolchain file produced by it...
- recipe 5, pybind11. Tests are not run or fail.
- recipe 6, CFFI. Tests are not run of fail.

**Comment by bast** [comment]
Problems are fixed or worked around or at least postponed in #424.

**Comment by bast** [comment]
Taken care of in #424, closing.
