### ISSUE TITLE
Compiler warning in chapter 3, recipe 2

### ISSUE THREAD

**Issue by robertodr** [dev-cafe/cmake-cookbook#390]
I think the return type is `PyObject *`:
```
C:/projects/cmake-cookbook-no-symlinks/chapter-03/recipe-02/c-example/hello-embedded-python3.c: In function 'main':
C:/projects/cmake-cookbook-no-symlinks/chapter-03/recipe-02/c-example/hello-embedded-python3.c:4:22: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
   wchar_t *program = PyUnicode_DecodeLocale(argv[0], NULL);
```

**Comment by bast** [comment]
If I apply this change then we get another warning from `Py_SetProgramName` which expects `wchar_t`. Of course I could take away that line although it says "optional but recommended".

**Comment by robertodr** [comment]
Um... The official example is, `Py_DecodeLocale` returns `wchar_t *`.
```
#include <Python.h>

int
main(int argc, char *argv[])
{
    wchar_t *program = Py_DecodeLocale(argv[0], NULL);
    if (program == NULL) {
        fprintf(stderr, "Fatal error: cannot decode argv[0]\n");
        exit(1);
    }
    Py_SetProgramName(program);  /* optional but recommended */
    Py_Initialize();
    PyRun_SimpleString("from time import time,ctime\n"
                       "print('Today is', ctime(time()))\n");
    if (Py_FinalizeEx() < 0) {
        exit(120);
    }
    PyMem_RawFree(program);
    return 0;
}
```
I think I switched to `PyUnicode_DecodeLocale` to fix an error on windows... I think we need to do:
```
PyObject *program = PyUnicode_DecodeLocale(argv[0], NULL);
wchar_t * program_name = PyUnicode_AsWideCharString(program, NULL);
```
and the use `program_name` in `Py_SetProgramName`.
https://docs.python.org/3/c-api/unicode.html#c.PyUnicode_AsWideCharString

**Comment by bast** [comment]
With these changes it builds without warnings. I postpone however wrapping this up since this example segfaults on my computer with a double free. I need to investigate more later.
