### ISSUE TITLE
Chapter 6 failure(s) on Appveyor

### ISSUE THREAD

**Issue by bast** [dev-cafe/cmake-cookbook#397]
We need to check why no other recipes are run.

**Comment by robertodr** [comment]
:face_with_thermometer:

**Comment by bast** [comment]
Only two recipes were run because the second failed thanks to `DIE_HARD`.

**Comment by bast** [comment]
Only 6/2 seems to be problematic and probably I will have to revert to previous formulation.

**Comment by bast** [comment]
Correction: 6/2 seems to fail on MSYS as a symptom of the python script failing. Investigating.

**Comment by bast** [comment]
I will probably simplify 6/2 to make it more explicit and repetitive, with the bonus of making it more robust against un-escaped strings in irrelevant variables contained in `VARIABLES`.
