### ISSUE TITLE
Chapter 8 issues on Appveyor

### ISSUE THREAD

**Issue by bast** [dev-cafe/cmake-cookbook#404]
List ported from #403:

#### Not Working (neither MSYS nor VS)
- Recipe 2. _Managing dependencies with a superbuild I. The Boost libraries_ With MSYS fails intermittently. Consider me befuddled, because I thought I had managed to found the correct grimoire to make this happen on Windows too...
- Recipe 6. _Managing your project as a superbuild_ It looks like Git invoked through CMake doesn't work.

#### Not Working (MSYS)
- Recipe 3. _Managing dependencies with a superbuild II. The FFTW library_ I think it's a problem with their `CMakeLists.txt` being a minimal subset of their configure file.

#### Taking outrageously long
- Recipe 5. _Managing dependencies with a superbuild IV. The HDF5 library_ Takes more than one hour and the job is killed.

**Comment by robertodr** [comment]
Closed with #439
