### ISSUE TITLE
Chapter 11 setup.py can call CMake with wrong generator

### ISSUE THREAD

**Issue by bast** [dev-cafe/cmake-cookbook#414]
I have observed this on MSYS where setup.py invoked nmake. I will try to solve this with an environment variable. This affects two recipes.

**Comment by bast** [comment]
At the same time I will rename `GENERATOR` to `CMAKE_GENERATOR` for more specificity of `setup.py`.

**Comment by robertodr** [comment]
I think Conda uses `GENERATOR` we might want to stick with that for uniformity.

**Comment by bast** [comment]
OK I agree, left it as `GENERATOR`. Also to have more concise Appveyor overview where very long variable names are not helpful to distinguish test lanes.
