### ISSUE TITLE
CircleCI does not seem to trigger on PRs

### ISSUE THREAD

**Issue by bast** [dev-cafe/cmake-cookbook#454]
Not sure whether sometimes or always but we have observed this in two recent PRs.

**Comment by robertodr** [comment]
CircleCI is triggering for PR I submit. Don't know if it's because the problem is fixed or because I submitted the PR.

**Comment by bast** [comment]
Let's see what happens when I submit a PR very soon.

**Comment by bast** [comment]
My PRs are not picked up.

**Comment by bast** [comment]
`build PRs from all forks` is now enabled and my PRs are picked up. Thanks! Closing.
